/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#3c0800',
        'inverse-primary': '#bcc2ff',
        'primary-fixed': '#dfe0ff',
        'on-error': '#ffffff',
        'surface-container-high': '#e7e8eb',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#8694ff',
        'outline': '#767684',
        'secondary-fixed-dim': '#ffb59f',
        'surface-dim': '#d9dadd',
        'tertiary-fixed-dim': '#ffb4a1',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#3a0a00',
        'tertiary': '#420a00',
        'surface-container-highest': '#e1e2e5',
        'outline-variant': '#c6c5d5',
        'surface-tint': '#4654bc',
        'on-primary': '#ffffff',
        'primary-container': '#142490',
        'error': '#ba1a1a',
        'on-secondary-fixed-variant': '#852400',
        'tertiary-container': '#671500',
        'surface-container-low': '#f2f3f6',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#2c3aa3',
        'on-error-container': '#93000a',
        'surface-variant': '#e1e2e5',
        'surface-bright': '#f8f9fc',
        'inverse-on-surface': '#f0f1f4',
        'surface-container': '#edeef1',
        'inverse-surface': '#2e3133',
        'on-surface': '#191c1e',
        'on-tertiary-fixed-variant': '#81280f',
        'on-secondary-container': '#5b1500',
        'background': '#f8f9fc',
        'primary-fixed-dim': '#bcc2ff',
        'tertiary-fixed': '#ffdbd1',
        'surface': '#f8f9fc',
        'secondary-container': '#fe6431',
        'on-primary-fixed': '#000b62',
        'secondary': '#ae3100',
        'on-tertiary-container': '#f17a5b',
        'on-secondary': '#ffffff',
        'on-background': '#191c1e',
        'primary': '#000d6b',
        'on-surface-variant': '#454653',
        'secondary-fixed': '#ffdbd0',
        'cargo-primary': '#000d6b',
        'cargo-secondary': '#ae3100',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
      keyframes: {
        popIn: {
          '0%': { opacity: '0', transform: 'scale(0.9) translateY(20px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        }
      },
      animation: {
        popIn: 'popIn 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      }
    },
  },
  plugins: [],
}
